create database abc_orders;

use abc_orders;

select * from orders limit 10;
describe orders;
describe products;
describe account;

set sql_safe_updates = 0;
update orders
set order_date = str_to_date(order_date,"%m/%d/%Y"),
	ship_date = str_to_date(ship_date,"%m/%d/%Y");

alter table orders
modify column order_date date,
modify column ship_date date;

-- checking for null values
select count(*) from orders 
where order_no is null;

-- checking for duplicates 
select order_no,count(order_no) from orders
group by order_no having count(order_no)>1;

-- checkinf if it is really duplicate value or not
select * from orders where order_no ="5768-2" or order_no="6159-2";

set sql_safe_updates = 1;

-- 1. What is the total revenue generated by each product category?
select product_category,
Round(sum(total),2) as revenue
from orders
join products
on orders.product_id = products.product_id
group by product_category;

-- How many unique products have been ordered?
select distinct(count(product_name)) as unique_products
from products;

-- What is the total revenue generated each year?
select extract(Year from order_date) Year,
	    format(sum(total),2) Revenue
from orders
group by Year;

-- 4. What is the date of the latest and earliest order?
select min(order_date) "Earliest date",
       max(order_date) "Latest date"
from orders;

-- 5. What product category has the lowest average price of products?
SELECT product_category,
	ROUND(AVG(retail_price), 2) Average_price
FROM orders
JOIN products
USING(product_id)
GROUP BY product_category
ORDER BY Average_price
LIMIT 1;

-- 6. What are the top 10 highest performing products?
SELECT product_name,
	ROUND(SUM(total), 2) Revenue
FROM orders
JOIN products
USING(product_id)
GROUP BY product_name
ORDER BY Revenue DESC
LIMIT 10;

-- 7 Show the total revenue and profit generated by each account_manager?
SELECT account_manager,
	ROUND(SUM(total), 2) Revenue,
        ROUND(SUM(total) - SUM(cost_price), 2) Profit
FROM orders
JOIN account
USING(account_id)
GROUP BY account_manager
ORDER BY Revenue DESC;

--  8. What is the name, city and account manager of the highest selling product in 2017?
SELECT product_name,
	city,
        account_manager,
        ROUND(SUM(total)) Revenue
FROM orders
JOIN products
USING(product_id)
JOIN account
USING(account_id)
WHERE EXTRACT(year from order_date) = 2017
GROUP BY product_name, city, account_manager
ORDER BY Revenue DESC
LIMIT 1;

-- 9. Find the mean amount spent per order by each Customer type?
SELECT customer_type,
	AVG(total) Average_amount
FROM orders
GROUP BY customer_type;





